# Generated by Django 3.1.5 on 2021-01-15 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210114_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
