# Generated by Django 3.1.5 on 2021-01-15 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210114_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='buyer_id',
        ),
    ]
