# Generated by Django 3.1.5 on 2021-01-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_products_buyer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
