# Generated by Django 3.1.5 on 2021-01-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210116_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='min_amount',
            field=models.IntegerField(),
        ),
    ]
