# Generated by Django 3.1.5 on 2021-01-16 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210116_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='lists_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='prod_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products_id', to='auctions.products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='listing',
        ),
    ]
