# Generated by Django 3.1.5 on 2021-01-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210116_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
