# Generated by Django 3.1.5 on 2021-01-17 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_products_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
